version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: banco_app
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - postgres
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: banco_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres:15
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  adminer:
    image: adminer
    container_name: laravel_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - laravel

volumes:
  banco_data:
  postgres_data:

networks:
  laravel:
